### ISSUE TITLE
delay for heartbeat in tests is inconvenient

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-pubsub#101]
In tests that use gossipsub, we have to sleep for a bit to wait for the heartbeats to set everything up properly. This is pretty inconvenient, as adding two seconds of wait time to every single test gets pretty expensive.

Is there a way to force this to happen immediately?

cc @vyzo

**Comment by vyzo** [comment]
~We could have an immediate setup on Join, which grafts some links for immediate use.~

edit: we already do that.

**Comment by vyzo** [comment]
Nevermind, we already do that.

**Comment by vyzo** [comment]
I think the issue may be that when the Joins happen, there are not enough peers that have propagated their subscriptions yet. 
We could make the initial heartbeat delay smaller than 1s however.
