### ISSUE TITLE
Optimize Validator Pipeline

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-pubsub#103]
Our validation pipeline is asynchronous: it spawns a goroutine for each incoming message, which may then get throttled based on topic and global limit throttles.
This creates a performance problem for message signature validation (#97) as we now have to enter the validation pipeline for every message when using signing (planned to become the default in ipfs and filecoin).

Proposed action:
- pre-spawn NUMCPU goroutines to handle the validation front-end.
- all signatures should be validated in the validation front-end goroutines
- create a distinction between synchronous and asynchronous validators (which may block and be otherwise slow due to network effects), such that:
  - synchronous validators are applied in the validation front-end
  - asynchronous validators are handled in a freshly spawned goroutine, limited by the throttles.

**Comment by aarshkshah1992** [comment]
@vyzo  I would like to work on this. Is this up for grabs ? Have read the go-libp2p pubsub code  and am looking for ways to contribute. This looks like a great first task !

**Comment by vyzo** [comment]
this is a relatively tricky issue to tackle for starting project -- and we are also not sure yet whether it is a problem.
