### ISSUE TITLE
[Question] Multiaddr of publisher available to subscriber

### ISSUE THREAD

**Issue by upperwal** [libp2p/go-libp2p-pubsub#109]
Hey!

Is multiaddr of the publisher available to the subscriber? What I can understand from the source is that ```Subscription.Next``` can get us ```peer.ID``` and not multiaddr. 

User case: If pubsub is used for peer discovery and subscriber whats to directly connect with the publisher.

Thanks

**Comment by vyzo** [comment]
You have the peer in the `From` field of the message, as bytes. 

Also see #97

**Comment by upperwal** [comment]
@vyzo thanks for the reply. 

Yeah, ```From``` only has ```peer.ID``` and not the ```Multiaddr``` of the publisher.

https://github.com/libp2p/go-floodsub/blob/0827f5e955d17c60f422db92d2536be7598b05a6/pubsub.go#L601-L608

I could not understand the reference to #97. Can you elaborate? Thanks.

**Comment by vyzo** [comment]
Oh, you want the address of that peer? 
That is generally not known to the pubsub system, unless it has a direct connection to it. 
You may be able to retrieve this from the DHT with `FindPeer`.

**Comment by upperwal** [comment]
yeah, that can be done. But what would be better

1. Including publisher's ```Multiaddr``` in pubsub message (and increasing the size of **flood** packets)
2. Call ```FindPeer``` and send a dht query which itself is expensive.

Is this use case (publisher wants to directly connect to the subscriber) even prominent?

Any thoughts @Stebalien @raulk

**Comment by vyzo** [comment]
It kind of defeats the purpose.
Also note that the address is a very loaded term -- it's not just one, there is a whole slew of them and including them in the pubsub message induces a lot of overhead.
Better to use the DHT, it was designed for this!

**Comment by upperwal** [comment]
yeah, agree.

**Comment by Stebalien** [comment]
Also, we can (and should) have non-DHT peer routing protocols.
