### ISSUE TITLE
question on floodsub and gossipsub compatibility question.

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-libp2p-pubsub#110]
Sorry in advance for bringing this as an issue, as it's probably a better candidate for a wiki.  I have a question: Is it intended that the `floodsub` and `gossipsub` protocols should be compatible?  Ie. if you develop an application that uses one, and you substitute the other for half the nodes - will the network still operate?  I understand that there are practical considerations about traffic volumes, etc, however my point is to ask whether the messages are compatible, such that a gossiped message sent by a node using `floodsub`, and received by a node which uses `gossipsub`, will be propagated by the second node, and whether that message can be propagated further.  Is this a design goal of the system?

**Comment by vyzo** [comment]
yes, absolutely! We want to have fully interoperable floodsub and gossipsub nodes, and an easy upgrade path.

**Comment by jvsteiner** [comment]
great, thanks!
