### ISSUE TITLE
Possible false positive ignore message

### ISSUE THREAD

**Issue by alanshaw** [libp2p/go-libp2p-pubsub#119]
I've just found in `js-libp2p-floodsub` that messages might be ignored when they shouldn't be.

We're doing something similar to:

https://github.com/libp2p/go-libp2p-pubsub/blob/107d351038ce677804e7a180429aff93fa98a2ab/pubsub.go#L460-L462

...but in JS, converting the `seqno` to utf8 string can sometimes result in the same string for different buffers. The following are two different seqno's that `js-ipfs` was sent from `go-ipfs` that demonstrates the problem:

```console
$ node
> const buf2 = Buffer.from('15603533e990dfe0', 'hex')
> const buf1 = Buffer.from('15603533e990dfde', 'hex')
> buf1.toString('utf8')
'\u0015`53���'
> buf2.toString('utf8')
'\u0015`53���'
> buf1.toString('utf8') === buf2.toString('utf8')
true
> 
```

So sometimes we think we've seen the message when we haven't! 🤦‍♂️ 

I'm flagging this here incase this could be a problem in Go as well...please feel free to close if you can determine it's not a problem :)

FYI for the PR to `js-libp2p-floodsub` I'll probably convert the seqno buffer to a hex encoded string instead.

refs https://github.com/libp2p/js-libp2p-floodsub/pull/59

**Comment by Stebalien** [comment]
This isn't an issue in go. In go, strings are "just bytes" so the encoding won't matter.

However, thanks for flagging (and catching) this!
