### ISSUE TITLE
Impersonating while sending a message

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#120]
Hello, I have a question. What happens if one (malicious) node starts sending a lot of message and sets the `From` field with another node's ID (let's call it node_victim)? When node_victim starts to send it's own messages, the messages will get discarded as the `func seenMessage` will return true on all other nodes. The malicious node also need to know the victim's current sequence but that will be trivial to find (get its last message and increment that sequence number).
Since I have opened this issue I also want to ask if there is a way to make the Message an interface rather than a struct. That would give the code the ability to introduce new features like message signing (and possibly easier way to circumvent the above mentioned problem)

**Comment by Stebalien** [comment]
1. We've recently merged message signing to handle this (see the `WithMessageSigning` option). It's currently off by default but I'd like to at least turn message *signing* on by default (even if we leave verification off until enough of the network has upgraded, see #121).

2. You can implement custom message validation with validators. These validators can deserialize the inner message itself to validate arbitrary constraints.

**Comment by iulianpascalau** [comment]
Ok, tried the newest version, with message signing ON and it is practically impossible to impersonate, tried it with tampered code to alter the message but it was filtered out by either line 64 on floodsub.go (peer id mismatch) or line 501 in pubsub.go (signature validation failed), so this is great! 
Thought of using Validators. Maybe caching the deserialized form as to not do the deserialization again. 
Ok, I think we can close the discussion on this topic. 
Thanks a lot. 
I still have some other questions regarding pubsub. Should I open issues, or may I contact you on your email?

**Comment by vyzo** [comment]
Please open issues, unless it is something very sensitive.
