### ISSUE TITLE
Signing on some topics

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#124]
Is it possible to reshape signing messages on pubsub as to turn signing on or off on topics rather than entire pubsub?
The reason behind this question is that there might be topics that do not need signing and the process of signing/validating induce unwanted overhead. As a practical example, one might implement a topic for broadcasting blockchain transactions that are known that are tampered proof and the originator peer node simply doesn't matter.
Of course there is a complication to this as the function `msgID` needs to compute the message ID in a different way. (may be a hash string of the payload when the message is not signed?)

**Comment by vyzo** [comment]
I am against such a change in principle -- we really want to sign everything and actively discourage unsigned messages with strict validation. 
The overhead of signatures when using ed25519 (or btc) keys is very small.

**Comment by iulianpascalau** [comment]
OK, thanks.
