### ISSUE TITLE
Messages are not received if len(message) >1048438 bytes

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#126]
Hello

I have found a new issue when receiving a message larger then 1048438 bytes (almost 1MB). The message gets trimmed and the signature will not appear valid. The issue comes from line 29 in comm.go where there is a delimiter of 2^20 bytes (1MB message size). Is this delimiter really necessarily? The underlying host object should take care of message fragmentation/flood protection/muxing and others.

Thanks.

**Comment by vyzo** [comment]
Yes, there is a limit for message size everywhere we use delimited readers, and that's the default max message size in libp2p.

The limit is there to protect the peer from memory use DoS attacks; otherwise a peer could just send a multi-gigabyte message that slowly consumes all memory and crashes.

**Comment by iulianpascalau** [comment]
Ok, but the host object should take care of that by marking the peer as a flood peer and closing its connection. Pubsub being an "application" over libp2p core should simply not care of this limitation. 
This restriction will somehow add some complexity as the message composed shall not exceed 1MB in size. If, for some reason, I have to send more data than 1MB, the program must fragment the data in more than 1 message and then the peer should be able to recompose back the original data from more messages received.

**Comment by vyzo** [comment]
This limit needs to be there otherwise the delimited reader will silently read the huge message and consume all the memory.

Yes, it adds complexity, but we can't not have a limit.

**Comment by vyzo** [comment]
Closing this, as I think it has been resolved.
