### ISSUE TITLE
if pubsub route loses remote peer connection information?

### ISSUE THREAD

**Issue by bruinxs** [libp2p/go-libp2p-pubsub#128]
### Version of go-ipfs 

<pre>
$ ipfs version --all
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
</pre>

### What I do

Peer A subscribes to a topic 'test_topic', and then peer B publish data to peer A to 'test_topic'. At the beginning, peer A can receive the data published by B, but after about 8 hours, peer B would publish data to peer A. At this time, A would not receive the data of peer B. 

(Note: the middle 8 hours peer B did not publish any data to peer A and I executed `ipfs swarm peers` on peer B to see the connection of peer A. I executed `ipfs pubsub peers` on peer B without seeing any output.).

Then, I am in the peer B execution `ipfs swarm disconnect <peer A>`, `ipfs swarm connect <peer A>`, at this time peer B re-publishes data to peer A, peer A can receive it. And I execute `ipfs pubsub peers` on peer B can see the id of peer A.

### Why?

I suspect that after the peer connection, when writing data to the peer, other non-network errors occurred, causing the peer to be removed from the pubsub route. But in the swap peers (dht route?) there is always a connection to the peer, so there is no new connection to the peer to cause the pubsub route to register the peer.

Reference source code：

* https://github.com/libp2p/go-libp2p-pubsub/blob/c9c04d42074b6673bb9f5a37de8f679ee8c262a4/notify.go#L18

* https://github.com/libp2p/go-libp2p-pubsub/blob/c9c04d42074b6673bb9f5a37de8f679ee8c262a4/pubsub.go#L264

* https://github.com/libp2p/go-libp2p-pubsub/blob/c9c04d42074b6673bb9f5a37de8f679ee8c262a4/comm.go#L81

* https://github.com/libp2p/go-libp2p-pubsub/blob/c9c04d42074b6673bb9f5a37de8f679ee8c262a4/pubsub.go#L280

**Comment by bruinxs** [comment]
Or can anyone tell me why it happened, thank you

**Comment by daviddias** [comment]
Hi @bruinxs! We did some spring cleanup in the repo issues. Let us know if the problem still persists and we will reopen (btw, there is a ton of updates on master that you might fancy checking out!)

**Comment by vans163** [comment]
I am seeing this on latest rc of 0.12, the peer constantly drops, if I manually readd the peer via swam connect it receives messages again.
