### ISSUE TITLE
support insecure connection 

### ISSUE THREAD

**Issue by yutongp** [libp2p/go-libp2p-pubsub#129]
pubsub uses `Conn.RemotePeer()` to get peer id as identifier in it's peer storage.
However, the [insecure](https://github.com/libp2p/go-conn-security/blob/master/insecure/insecure.go) implementation `RemotePeer()` always returns an empty peer id.

I think if support insecure connection is desired behavior, we can use remote address as identifier in peer storage for insecure connection. Or, if pubsub decides not to support insecure connection at all due to some concerns, an error return in the constructor is much friendly compare to failing the publish event with only `nil` peer id in peer store.

**Comment by Stebalien** [comment]
> I think if support insecure connection is desired behavior,

Insecure really just exists for debugging. However, to make it *work* properly for debugging, we probably need to fix https://github.com/libp2p/go-libp2p/issues/452.

I'm going to close this issue in favor of that one as this is a more general problem (and we can't really expect libp2p services to work without *some* peer ID).
