### ISSUE TITLE
Protocol for sending a messaging to the entire network

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p-pubsub#136]
I want to implement a gossip/flooding functionality similar to how Bitcoin gossips a mined block to the entire network. Any peer in the network should be able to send a message to the entire network. I think go-libp2p-pubsub is a great fit for this as I can simply get all peers to subscribe to the same topic. Would there be any advantages/disadvantages of choosing GossipSub over Floodsub for this ?

**Comment by vyzo** [comment]
yes, gossipsub scales much better than floodsub as it bounds the node degree.

**Comment by aarshkshah1992** [comment]
@vyzo  But does the bounded degree matter if we need to send the message to every peer in the network ?

**Comment by vyzo** [comment]
yes of course, as it bounds the numbers of messages sent; floodub can send O(n^2) messages -vs- O(cn) in gossipsub, where c is the bound.
