### ISSUE TITLE
Documentation regarding subscription to a new topic

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#144]
Hello
If it is possible, maybe, to add a few lines on pubsub.go:721 (comment regarding Subscribe func) in which it should warn that the subscription is not done instantaneous? 
The reason I'm asking this is that on a high-performance machine the subscription is done very fast and the tests we wrote work but when running same tests on a low performance machine (eg. on a docker), *sometimes*, *some tests* would failed. After introducing a `time.Sleep` of aprox. 1 sec between subscription on topics and publishing some data, tests started to work as expected on the docker machine. 

Thanks.

**Comment by vyzo** [comment]
We can do that.

**Comment by vyzo** [comment]
#145 adds some documentation.
