### ISSUE TITLE
Duplicate blacklist check in pubsub

### ISSUE THREAD

**Issue by paralin** [libp2p/go-libp2p-pubsub#153]
https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L294

```
			if p.blacklist.Contains(pid) {
				log.Warning("already have connection to peer: ", pid)
				continue
			}

			if p.blacklist.Contains(pid) {
				log.Warning("ignoring connection from blacklisted peer: ", pid)
				continue
			}
```

The second if should always be false, correct?

blame cc @vyzo

**Comment by vyzo** [comment]
Ugh, the first one should be a check in the connection table; thanks for catching.

**Comment by vyzo** [comment]
#154 fixes it.

**Comment by vyzo** [comment]
this bug came to existence when the blacklist was promoted to an interface; initially there were two map checks, and they became two checks on the same object.
