### ISSUE TITLE
Exporting funcs in sign.go

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#157]
Hello
I was wondering if funcs inside sign.go could be made exported as their functionality might be reused in some other situations. Just to mention, I have done a direct send struct that will send direct messages between peers but I want to be able to sign/verify messages as to be 101% sure that someone did not interposed between those 2 peers. So, I have reused the pubsub_pb.Message struct for serializing/deserializing the data and could have used the signing and verifying from sign.go. Right now, I have copied the funcs from sign.go but that seems rather awkward since the project now uses duplicate code.
Or even better, since there is a wrapper over pubsub_pb.Message called pubsub.Message, might add there 2 functions for signing and verifying the signature.

**Comment by vyzo** [comment]
Sure, we could export those, although it's a fringe use case.

**Comment by iulianpascalau** [comment]
End up by discarding message signing/verifying on direct sent -> direct received messages as there is already an authentication mechanism when the handshake between those 2 peers takes place. 
Thanks.
