### ISSUE TITLE
Questions on the difference between notifySubs and Publish

### ISSUE THREAD

**Issue by nairan** [libp2p/go-libp2p-pubsub#159]
Noob question - Inside publishMessage (pubsub.go), the mentioned two calls are one after the other. Both seem handing messages to subscribers, but placing messages in different places. What is the connection and difference between these them? Thank you.

**Comment by vyzo** [comment]
One call (`notifySubs`) is used to deliver the message locally, the other call passes the message to the router for forwarding.

**Comment by daviddias** [comment]
Question answered, @nairan let us know if you have any follow up questions.
