### ISSUE TITLE
Race detector unhappy in tests

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-pubsub#167]
Running tests with the race detector (#166) uncovered two issues:

1. Data race:

```
=== RUN   TestGossipsubFanoutExpiry
==================
WARNING: DATA RACE
Write at 0x00c000240e70 by goroutine 539:
  runtime.mapdelete_faststr()
      /usr/local/Cellar/go/1.12/libexec/src/runtime/map_faststr.go:297 +0x0
  github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:435 +0xf38
  github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat-fm()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:382 +0x41
  github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:401 +0xc69

Previous read at 0x00c000240e70 by goroutine 1369:
  github.com/libp2p/go-libp2p-pubsub.TestGossipsubFanoutExpiry()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:300 +0x9b2
  testing.tRunner()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0x163

Goroutine 539 (running) created at:
  github.com/libp2p/go-libp2p-pubsub.NewPubSub()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/pubsub.go:210 +0xf26
  github.com/libp2p/go-libp2p-pubsub.NewGossipSub()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub.go:49 +0x3f6
  github.com/libp2p/go-libp2p-pubsub.getGossipsubs()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:17 +0x15f
  github.com/libp2p/go-libp2p-pubsub.TestGossipsubFanoutExpiry()
      /Users/raul/go/src/github.com/libp2p/go-libp2p-pubsub/gossipsub_test.go:265 +0x175
  testing.tRunner()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0x163

Goroutine 1369 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:916 +0x699
  testing.runTests.func1()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:120 +0x222
==================
```

2. Goroutine threshold exceeded for race detector. See this PR where a similar issue was resolved: https://github.com/libp2p/go-libp2p-transport/pull/47.

```
=== RUN   TestGossipsubControlPiggyback
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

**Comment by vyzo** [comment]
Issue 2 is not resolvable, we do fire more than 8128 goroutines in that test.

**Comment by vyzo** [comment]
Issue 1 is not a bug in the core code, but a fluke in the test which accesses state outside the event loop for test purposes.

**Comment by vyzo** [comment]
Can't resolve either of these issues unfortunately.

**Comment by raulk** [comment]
> Issue 2 is not resolvable, we do fire more than 8128 goroutines in that test.

The solution is to detect when we’re running under the race detector and downscale the concurrency. See https://github.com/libp2p/go-libp2p-transport/pull/47 for an example.

---

About issue 1, gotcha. Let’s skip that test under the race detector then.

**Comment by vyzo** [comment]
> The solution is to detect when we’re running under the race detector and downscale the concurrency

That's like standing on your head to satisfy a tool. Also, the test will probably not be effective.

**Comment by raulk** [comment]
@vyzo it’s a useful tool. How about two tests: current version when we’re not running with the race detector, and downscaled version when we are? That’s the best of both worlds.

**Comment by vyzo** [comment]
I would say just disable the race detector for that test too. The tool is useful, but I am not fond of making alchemies to satisfy it.

**Comment by raulk** [comment]
That precludes the test from ever running on CI, which I don’t think is what we want?

**Comment by vyzo** [comment]
Can't we selectively disable it?

**Comment by vyzo** [comment]
Also I want to run all tests on CI; if the race detector can't handle them, then turn it off.

**Comment by raulk** [comment]
CI always run tests with the -race flag now. Ideally we’d run tests with and without the race detector to discriminate heisenbugs, but at the expense of increasing build time by 2x. Would that help?

Discard the two tests idea — still won’t help in CI. My brain is fried from all the gomodding 🙃

**Comment by vyzo** [comment]
Running 2x is probably an ok solution.

**Comment by Kubuxu** [comment]
Reducing the number if sent messages makes the race detector not freak out in 2.

My solution for test number 1 would be: Add those tests in a separate file, with `!race` build tag. I will update `ci-helper` to check if any such tests exist and run them without race detector.

**Comment by vyzo** [comment]
I have fixed the test race and disabled the problematic test in #178.
