### ISSUE TITLE
Couldn't figure out how to make pubsub work, need help.

### ISSUE THREAD

**Issue by Ajkcki** [libp2p/go-libp2p-pubsub#182]
I'm trying to modify the echo example in go-libp2p-examples to make it work with pubsub. After quite a few hours, I couldn't make it work. I don't know where to ask for help, so here is my question: can anyone please write an example to show how to use this package? If anyone can help me make my code work, it can serve as an example for others.

`go run main.go -l 30000` will start a subscriber, say on address "/ip4/127.0.0.1/tcp/30000/ipfs/QmXmJhfqtKpkqq8QbcX6Bau6GF6m488umP6D1uukLEbaZf"

then start another instance on another terminal as `go run main.go -l 30001 -d /ip4/127.0.0.1/tcp/30000/ipfs/QmXmJhfqtKpkqq8QbcX6Bau6GF6m488umP6D1uukLEbaZf`

The second instance published a message, and the subscriber was supposed to receive it. But that never happened, the subscriber waited on `msg, err := sub.Next(ctx)` forever.

```
func main() {
	ctx := context.Background()
	// LibP2P code uses golog to log messages. They log with different
	// string IDs (i.e. "swarm"). We can control the verbosity level for
	// all loggers with:
	golog.SetAllLoggers(gologging.INFO) // Change to DEBUG for extra info
	// Parse options from the command line
	listenF := flag.Int("l", 0, "wait for incoming connections")
	target := flag.String("d", "", "target peer to dial")
	insecure := flag.Bool("insecure", false, "use an unencrypted connection")
	seed := flag.Int64("seed", 0, "set random seed for id generation")
	flag.Parse()


	if *listenF == 0 {
		log.Fatal("Please provide a port to bind on with -l")
	}

	// Make a host that listens on the given multiaddress
	ha, err := makeBasicHost(ctx, *listenF, *insecure, *seed)
	if err != nil {
		log.Fatal(err)
	}

	topic := "foobar"
	data := []byte("this is a message")

	if *target == "" {
		log.Println("listening for connections")
		//select {} // hang forever
		ps, err := pubsub.NewFloodSub(ctx, ha)
		if err != nil {
			panic(err)
		}
		sub, err := ps.Subscribe(topic)
		if err != nil {
			panic(err)
		}

		for {
			msg, err := sub.Next(ctx)
			if err != nil {
				panic(err)
			}
			if msg.Signature == nil {
				panic("no signature in message")
			}
			if string(msg.Data) != string(data) {
				panic("unexpected data")
			}
		}
		os.Exit(0)
	}
	/**** This is where the listener code ends ****/

	// The following code extracts target's the peer ID from the
	// given multiaddress
	ipfsaddr, err := ma.NewMultiaddr(*target)
	if err != nil {
		log.Fatalln(err)
	}

	pid, err := ipfsaddr.ValueForProtocol(ma.P_IPFS)
	if err != nil {
		log.Fatalln(err)
	}

	peerid, err := peer.IDB58Decode(pid)
	if err != nil {
		log.Fatalln(err)
	}

	// Decapsulate the /ipfs/<peerID> part from the target
	// /ip4/<a.b.c.d>/ipfs/<peer> becomes /ip4/<a.b.c.d>
	targetPeerAddr, _ := ma.NewMultiaddr(
		fmt.Sprintf("/ipfs/%s", peer.IDB58Encode(peerid)))
	targetAddr := ipfsaddr.Decapsulate(targetPeerAddr)

	// We have a peer ID and a targetAddr so we add it to the peerstore
	// so LibP2P knows how to contact it
	ha.Peerstore().AddAddr(peerid, targetAddr, pstore.PermanentAddrTTL)
	fmt.Println(peerid)
	fmt.Println(targetAddr)

	pub, err := pubsub.NewFloodSub(ctx, ha)
	if err != nil {
		panic(err)
	}

	err = pub.Publish(topic, data)
	if err != nil {
		panic(err)
	}
}
```

**Comment by vyzo** [comment]
You need to connect the nodes after constructing the pubsub objects.
Also, please _do not_ construct the basic host directly, this is an internal detail. Use the libp2p constructor with `libp2p.New` to construct hosts.

**Comment by Ajkcki** [comment]
vyzo, Thank you for the response. Now I connect to the subscriber right after constructing the pubsub object
```

        pub, err := pubsub.NewFloodSub(ctx, ha)
	if err != nil {
		panic(err)
	}

	pinfo := ha.Peerstore().PeerInfo(peerid)
	err = ha.Connect(ctx, pinfo)
	fmt.Println(pinfo)
	if err != nil {
		panic(err)
	}

       err = pub.Publish(topic, data)
	if err != nil {
		panic(err)
	}
```
The server did respond, but with error

`23:48:40.758  INFO     pubsub: error reading rpc from Qmard2u18iv3v7iLmEG3NVHzE8Sw9yKfz65ecUm9v1bHQw: stream reset comm.go:38`

That happened because when the second instance exited, it closed the connection. Any idea how to fix it?

BTW:  `makeBasicHost(ctx, *listenF, *insecure, *seed)` is copied from the echo example, it indeed uses `libp2p.New` to construct a new host, I didn't bother to post the source in my first post. But here it is

```
func makeBasicHost(ctx context.Context, listenPort int, insecure bool, randseed int64) (host.Host, error) {

	// If the seed is zero, use real cryptographic randomness. Otherwise, use a
	// deterministic randomness source to make generated keys stay the same
	// across multiple runs
	var r io.Reader
	if randseed == 0 {
		r = rand.Reader
	} else {
		r = mrand.New(mrand.NewSource(randseed))
	}

	// Generate a key pair for this host. We will use it at least
	// to obtain a valid host ID.
	priv, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, r)
	if err != nil {
		return nil, err
	}

	opts := []libp2p.Option{
		libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", listenPort)),
		libp2p.Identity(priv),
		libp2p.DisableRelay(),
	}

	if insecure {
		opts = append(opts, libp2p.NoSecurity)
	}

	basicHost, err := libp2p.New(ctx, opts...)
	if err != nil {
		return nil, err
	}

	// Build host multiaddress
	hostAddr, _ := ma.NewMultiaddr(fmt.Sprintf("/ipfs/%s", basicHost.ID().Pretty()))

	// Now we can build a full multiaddress to reach this host
	// by encapsulating both addresses:
	addr := basicHost.Addrs()[0]
	fullAddr := addr.Encapsulate(hostAddr)
	log.Printf("I am %s\n", fullAddr)
	if insecure {
		log.Printf("Now run \"./echo -l %d -d %s -insecure\" on a different terminal\n", listenPort+1, fullAddr)
	} else {
		log.Printf("Now run \"./echo -l %d -d %s\" on a different terminal\n", listenPort+1, fullAddr)
	}

	return basicHost, nil
}

**Comment by vyzo** [comment]
that log is just an informational log message, it's not an error by any means.

**Comment by Ajkcki** [comment]
Thank you so much vyzo, everything seems to be working now. I have one further questions though, how should I manage all the connections? I thought once I put a peer's address into `Peerstore`, libp2p will automatically take care of connecting to, checking the status of (ping/pong), reconnecting to all the peers.  Apparently this is not the case.

**Comment by vyzo** [comment]
No, this is not the case.
In the echo example, there is an implicit connection when opening a new stream, which uses the information in the address book.
Pubsub can't do that, we can't start randomly connecting to peers for which we have addresses in the address book. Instead we rely on the user to provide a bootstrap mechanism that establishes connections as needed.

**Comment by Ajkcki** [comment]
Got it, thanks. Once connected, do you auto-reconnect if the connection is lost, say because of some network problem?

**Comment by vyzo** [comment]
Unfortunately there is no auto-reconnection.

**Comment by Ajkcki** [comment]
Thanks. So I have to manage the connections myself. I'll try to do it, and if I would encounter further problems, I'll ask for help.

**Comment by Stebalien** [comment]
(closing for tracking)
