### ISSUE TITLE
Add Associated Data

### ISSUE THREAD

**Issue by keks** [libp2p/go-libp2p-pubsub#19]
I propose adding something like associated data. It is kept up-to-date using application-specific logic and sent to peers that subscribe. This could be a string that describes what the topic is about or anything else. Basically an `interface{}` value.

## Motivation
In Orbit we face the problem that a peer kind of sits in the dark after subscribing a topic. It doesn't have access to history until someone who has witnessed previous messages publishes a new message. That message will contain references to one or more most recently seen messages. The new peer can follow these messages and reconstruct history. However, it needs someone to post something to do that.

Instead it would be nice to get that information at subscribe time. That is why I would like to see an AD field that can be set by the application that subscribes to this.

I talked to @haadcode about this and he likes the idea.

### How will this play with signing/encryption?
Not sure. I don't think I really got the auth part yet. Is there a hard-ish spec somewhere for encrypted/auth'd topics?
Anyway, I suspect if we do things the right way, the worst a byzantine node could do is to withhold updates to the AD field, which I would rate equal to not forwarding messages, which can still happen. So it shouldn't be a big problem.

**Comment by whyrusleeping** [comment]
This is an interesting idea. How would this information get propogated? Who is responsible for the most up to date value?

**Comment by vyzo** [comment]
Closing, as this is out of scope.
