### ISSUE TITLE
message arrival rate

### ISSUE THREAD

**Issue by wenchaopeng** [libp2p/go-libp2p-pubsub#191]
Is it possible to ensure that all messages are received when sending a large number of messages from one node to multiple nodes?
I tested it and found that some messages were not received.

**Comment by raulk** [comment]
@pwc5232759 We need some more details of your setup to be able to help you, e.g. pubsub router you're using, message rate, what the network looks like (is this on the public libp2p network or not?), how are topic members finding each other, is this a single topic? Also describe the kind of message loss you see. Also, enable the `INFO` log level (one quick way to do it is to set the `IPFS_LOGGING=info` environment variable), and monitor the output for messages like this: https://github.com/libp2p/go-libp2p-pubsub/blob/4221a3966bf2bf3f915fcd6623c6bde688d99556/gossipsub.go#L348.

**Comment by wenchaopeng** [comment]
ok, I will provide it later, thank you for your reply.
