### ISSUE TITLE
Not filling mesh peers if there are less than `D` of them when joining a topic

### ISSUE THREAD

**Issue by NIC619** [libp2p/go-libp2p-pubsub#194]
### What is wrong?
In `GossipSubRouter.Join()` if there are fanout peers but not enough of them, it won't `selects the remaining number of peers (D-x) from peers.gossipsub[topic]` as suggested in the [spec](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub#topic-membership).
https://github.com/libp2p/go-libp2p-pubsub/blob/4221a3966bf2bf3f915fcd6623c6bde688d99556/gossipsub.go#L269-L274

**Comment by raulk** [comment]
Hey @vyzo, is there a misalignment between implementation and spec?

**Comment by vyzo** [comment]
it's a minor bug I would say.

**Comment by raulk** [comment]
@vyzo 

> it's a minor bug I would say.

Please elaborate. OP probably wants to understand impact and where the bug is: in the spec or the implementation.

**Comment by vyzo** [comment]
The bug is in the implementation.
The mesh should be filled at D peers if the fanout peers are less, which is what the spec says.
The impact is minimal, the next heartbeat will fill the mesh.

**Comment by raulk** [comment]
@vyzo — let’s fix the implementation promptly. Several teams are using this as the reference implementation, and it creates confusion, despite the impact being minimal, in theory.

**Comment by vyzo** [comment]
Added some code to handle this in #196.
