### ISSUE TITLE
HEARTBEAT in Gossipsub not working 

### ISSUE THREAD

**Issue by rairyx** [libp2p/go-libp2p-pubsub#195]
I have 3 nodes, one is boot node, the other 2 nodes are connected to the boot node. All 3 nodes are subscribed to a same topic by gossipsub. I want 2 non boot nodes to exchange messages with each other. 
Upon connection, only one of the non bootnode had HEARTBEAT, 
`HEARTBEAT: Add mesh link to QmehVYruznbyDZuHBV4vEHESpDevMoAovET6aJ9oRuEzWa in RDEpsjSPrAZF9JCK5REt3tao gossipsub.go:406`
the other 2 nodes had no HEARTBEAT, only one node(the one with heartbeat) can send messages to the other via bootnode. The other one without heartbeat can not send message, as 
there are no peers in the mesh.   
After a few minutes, the boot node got 2 heartbeat and added 2 other nodes to it's mesh peer. 
But the third node still couldn't have heartbeat thus couldn't send messages. 
The code is based on [https://github.com/libp2p/demo-multi-lang/blob/master/pubsub/pubsub-interop.go](https://github.com/libp2p/demo-multi-lang/blob/master/pubsub/pubsub-interop.go)
Except I replaced floodsub with gossipsub. 
 `gsub, err := gossipsub.NewGossipSub(ctx, host, gossipsub.WithMessageSigning(false))`
I wander if there is something wrong with this scenario or I missed something?

**Comment by raulk** [comment]
@vyzo – could you have a look, please?

**Comment by vyzo** [comment]
weird, anything more to reproduce?

**Comment by rairyx** [comment]
@vyzo When there 3 nodes connected to the boot node, after a few 4-5 minutes, the boot node will stop working, then none of the nodes can send messages. The rest of nodes would print out error
`18:08:16.203 DEBUG     pubsub: PEERDOWN: Remove disconnected peer QmehVYruznbyDZuHBV4vEHESpDevMoAovET6aJ9oRuEzWa gossipsub.go:85
18:08:16.204  INFO     pubsub: error reading rpc from QmehVYruznbyDZuHBV4vEHESpDevMoAovET6aJ9oRuEzWa: stream reset comm.go:40`

Sometimes one of the nodes prints out:
```
0:52:49.054  INFO     swarm2: got error on dial: failed to negotiate security protocol: context deadline exceeded swarm_dial.go:420
10:52:49.054 DEBUG     swarm2: [limiter] clearing all peer dials: QmehVYruznbyDZuHBV4vEHESpDevMoAovET6aJ9oRuEzWa limiter.go:200
bootstrapping to peer failed:  failed to dial : all dials failed
  * [/ip4/127.0.0.1/tcp/5555] failed to negotiate security protocol: context deadline exceeded
```
This error here seemed that it took down the boot node, but sometimes when there are no visible errors on the non boot nodes, the boot node still fails.
"QmehVYruznbyD***" is the boot node.

When there are less than 3 nodes connecting to boot nodes, it seems fine.

**Comment by raulk** [comment]
@vyzo — nudge.

**Comment by raulk** [comment]
@rairyx — the issue you report is so specific, we’d benefit from seeing the code. Is is public? My best guess is that your peers are not connecting to one another (via, for example, random walks), and are instead in a hub-and-spoke topology. When the hub dies, the spokes cannot intercommunicate. What I don’t know is why the bootnode stops working, so seeing the code would help tremendously.

**Comment by rairyx** [comment]
@raulk Thanks for your reply! 
Yes this is in a hub-and-spoke topology
Here is the code, https://github.com/rairyx/raven/blob/gossipsub/pubsub/raven.go. The above issue are with the original latest go-libp2p-pubsub module, without dandelion integration.

**Comment by rairyx** [comment]
@raulk @vyzo  any clues?

**Comment by aschmahmann** [comment]
@rairyx Does your code actually function with Floodsub instead of Gossipsub, or does it get the same errors? Both your code and https://github.com/libp2p/demo-multi-lang augmented with a Port argument seem to fail on the subsequent Connects (before PubSub is even started).

I suspect this has to do with the bootstrapper running `for true {}` and eating up all the CPU time doing nothing. This is why `for true {}` isn't great, and `select {}` is preferred (https://stackoverflow.com/questions/18661602/what-does-an-empty-select-do).

Thanks for the bug report for https://github.com/libp2p/demo-multi-lang

**Comment by rairyx** [comment]
@aschmahmann Yes it works!! `for true{}` seems exactly the cause. Thank you very much! 
As I remember my code works with Floodsub.
