### ISSUE TITLE
Configurable Heartbeat Interval

### ISSUE THREAD

**Issue by ZenGround0** [libp2p/go-libp2p-pubsub#212]
I'd like to be able to configure the gossipsub router's heartbeat interval.  This is motivated by setting up local testing networks.  The current interfaces don't give me a way to block until the mesh overlay is setup which I need to block on before publishing because of the behavior in #211.  This mesh setup doesn't happen until the first heartbeat (the initial delay doesn't help because it is sometimes called before the first `Join`), and the default interval of 1 second is a bit too long for tests.

**Comment by vyzo** [comment]
The heartbeat interval is already configurable through the `GossipSubHeartbeatInterval` variable!
