### ISSUE TITLE
Expose the peer that delivered the message

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p-pubsub#215]
It may be useful for peers that want to layer protocols on top of pubsub to know which peer actually delivered a message to them.

We already have this information available in the `from` field of the RPC:

https://github.com/libp2p/go-libp2p-pubsub/blob/2247a54a8cfc7f84d54d28429a60fa4ce89d5c43/pubsub.go#L144-L149

so this would mean making the information publicly available in the Message struct:

https://github.com/libp2p/go-libp2p-pubsub/blob/2247a54a8cfc7f84d54d28429a60fa4ce89d5c43/pubsub.go#L136-L138

**Comment by aschmahmann** [comment]
@raulk @vyzo @ZenGround0

Do we think this is sufficiently reusable such that we're better off recommending this approach rather than the hackier, but already available, approach of using the validators? Note, that the validators take the peer that delivered the message as an input so we actually already have an avenue for getting the `from` into application space.

**Comment by vyzo** [comment]
Using the validators is just too hacky, let's expose `from`.

**Comment by raulk** [comment]
Closed in #218.
