### ISSUE TITLE
Signatures over protobuf-serialized data are not deterministic

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-pubsub#219]
* As a result of protobuf serialisation not being canonical.
* [This gist](https://gist.github.com/kchristidis/39c8b310fd9da43d515c4394c3cd9510) collects notes on this issue.
* May be a non-issue in practice, given that we don't use problematic field types (e.g. maps), but protobuf implementations may play tricks on us. Unlikely, but the spec doesn't prevent against it.

**Comment by vyzo** [comment]
In practice it is not a problem because we don't use any fancy data structures.
