### ISSUE TITLE
TestSubscribeMultipleTimes hangs occasionally

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-pubsub#22]
Must be some sort of race condition, but this test hangs for me maybe one in ten times

**Comment by Stebalien** [comment]
This is getting *really* annoying...

**Comment by vyzo** [comment]
I see a new behaviour on travis -- a SIGQUIT!

**Comment by whyrusleeping** [comment]
SIGQUIT? I think that means OOM...

**Comment by Stebalien** [comment]
> SIGQUIT? I think that means OOM...

Is that not just a timeout? I assume go test does that to dump a stack trace.

**Comment by whyrusleeping** [comment]
ooooooh, youre right.

**Comment by vyzo** [comment]
ok, that would explain it.

**Comment by vyzo** [comment]
I've been seeing it quite often on travis too.

**Comment by daviddias** [comment]
Follow on https://github.com/libp2p/go-libp2p-pubsub/issues/202
