### ISSUE TITLE
How to unsubscribe a topic simply using pubsub instead of using router?

### ISSUE THREAD

**Issue by Ziwei-Wei** [libp2p/go-libp2p-pubsub#221]
There is not an unsubscribe method to use for the pubsub struct. However, there is a Router interface which has a Leave method implemented by the GossipSubRouter and the FloodSubRouter(although it is an empty method). If I have to use the unsubscribe functionality, then I have to avoid construct my pubsub directly using pubsub.NewGossipSub because I need to use my router to unsubscribe the topic.

**Comment by aschmahmann** [comment]
The subscription object has a `Cancel()` function that you can call.

**Comment by Ziwei-Wei** [comment]
@aschmahmann Yes, that is exactly how I use the pubsub library right now. I have to sustain a  `subMap  map[string]*pubsub.Subscription` with `pubsub  *pubsub.PubSub` to be able to close subscriptions and do other stuff, but the pubsub object actually already has `myTopics map[string]map[*Subscription]struct{}` in the pubsub struct which did not expose enough method to use directly. I just feel like it will be easier and intuitive to use if it can have these functionalities.

**Comment by Stebalien** [comment]
The point of subscribing to a topic is to receive messages on that topic. To do that, you need the subscription object. I'm not sure how you could use pubsub _without_ storing these Subscription objects somewhere.

Additionally, the pubsub service is designed to be usable by multiple services/apps at once. Providing a cancel method on the PubSub instance itself would make it easy for services to accidentally interfere with each other.

I'm closing this as "wontfix" as it seems contrary to how PubSub was designed to be used. If I'm misunderstanding something, please correct me.

**Comment by Ziwei-Wei** [comment]
Thank you for the clarification! I can now understand this design.
