### ISSUE TITLE
Separating Meshsub from Gossipsub

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p-pubsub#249]
## Proposal

Have a topic option that can be read by Gossipsub that instead of emitting gossip sends the entire message

## Background

Gossipsub has two major improvements over Floodsub.
1) Mesh behavior
    - Gossipsub creates a mesh structure by, for each peer, defining a subset of the peers it's connected to as its "mesh peers"
    - Messages are only consistently forwarded to the mesh peers
    - Messages are occasionally sent to a subset of the peers not in the mesh
2) Gossip behavior
    - The messages that are occasionally sent are sent in two phases
        - First peers advertise that they have a message
        - Then if a peer wants the message being advertised they ask for it and it is sent to them

## Motivation

There may be protocols designed where the messages being propagated are very small. In these cases Gossipsub's IHAVE/IWANT "gossip" is harmful since nodes have to wait an extra roundtrip to get the data and extra bandwidth is consumed by the IHAVE/IWANT messages. However, switching to Floodsub is inefficient because we still have to broadcast to the entire network.

## Alternatives

- Create a new router for this functionality
    - Requires either adding it to this repo and maintaining it or landing something like #199 
    - Requires either
       - copy-pasting most of the gossipsub code and maintaining it, or
       - abstracting the mesh code from the gossip code (would look similar to the proposal)
- Allow topic options to specify which router to use

@vyzo thoughts?

**Comment by vyzo** [comment]
I am not convinced it's a good idea; gossip is very much essential for a healthy mesh.

**Comment by vyzo** [comment]
Let me elaborate on that a bit: the mesh might form disconnected (unlikely as it might be), and gossip can help correct such pathologies. Furthermore, the next iteration of gossipsub will act upon gossip to heal broken meshes.

**Comment by aschmahmann** [comment]
@vyzo maybe I wasn't being clear. I'd still like to do the `emitGossip` step, however instead of sending a list of IHAVEs and receiving a list of IWANTs I'd just send a list of messages.

AFAIU we could still use the gossip like properties for episub improvements. This is just an optimization that saves a roundtrip for very small messages, and that would be a waste of bandwidth for large messages.

**Comment by vyzo** [comment]
The messages would have to be very small for this to make sense -- smaller than the message IDs, which aren't all that big.
