### ISSUE TITLE
Who is peer.ID in Validator?

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p-pubsub#250]
https://github.com/libp2p/go-libp2p-pubsub/blob/7e5b02f152ae2dd8bceb897affe7ef57cb3c6b4e/validation.go#L17-L18

Based on my experimentation, it looks like peer.ID is always my peer.ID, which I found very confusing.

**Comment by prestonvanloon** [comment]
To add a bit more context, I had a validator that would reject messages from myself. As a result, my peers were not receiving my messages. I am not sure if this validation is supposed to run on outgoing messages.

**Comment by vyzo** [comment]
The validator runs in all messages, including the ones you publish; the `peer.ID` in the signature is the peer the message was received from.

**Comment by prestonvanloon** [comment]
In our use case, this is wasteful. Is there any way to disable that functionality? 
We only want to validate incoming messages.

**Comment by aschmahmann** [comment]
@prestonvanloon you could get around this by adding a couple of lines at the start of your validator function to just check if the peerID matches your own and if so return true.

**Comment by prestonvanloon** [comment]
That’ll work, thank you!
