### ISSUE TITLE
Notify pruned peers of the backoff period

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-pubsub#286]
When we prune peers we have a backoff period, during which we won't re-GRAFT the pruned peer.
Furthermore, with #284 we have added GRAFT flood protections so that peers who send us GRAFTs too fast get penalized for quite a while.
From all this, it has become quite obvious that we should send the backoff period back to the pruned peer so that it knows when it's safe for it to re-attempt a GRAFT.
This will protect us from bugs that might arise because of a mismatch in the backoff period between peers, and also more clearly mark backoff violating peers for penalties, simplifying the logic somewhat.

The only downside is that it will take a (small, non-breaking) wire protocol change.

**Comment by dirkmc** [comment]
Currently IIUC we extend the backoff each time a peer tries to GRAFT too early.
We may want to consider not extending the backoff period if a peer asks to GRAFT too soon (unless they do it too frequently, which we are now checking for)

**Comment by vyzo** [comment]
I think we do want the behaviour of extending the backoff period when pruning for two reasons:
- we make sure we don't try to GRAFT while the other side is still backing us off
- we stop GRAFT floods dead in their tracks; basically a selfish or malicious peer trying to GRAFT its way in won't have any luck getting in.
