### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by dirkmc** [libp2p/go-libp2p-pubsub#287]
This issue tracks improvements in test coverage for
- [x] score.go (started at 32%)
- [x] score_params.go (started at 12%)
- [x] gossipsub.go (started at 63%)
- [x] trace.go (started at 58%)
- [x] tracer.go (started at 0%)
- [x] pubsub.go (started at 73%)
- [x] validation.go (started at 57%)
- [x] randomsub.go (started at 0%)

**Comment by vyzo** [comment]
We are a little over 82% now, which was the target (80%) for the big test writing push.
We have achieved satisfactory coverage, so I will close the issue.

Great job fellas!
