### ISSUE TITLE
remove panic inducing depencency 

### ISSUE THREAD

**Issue by fxfactorial** [libp2p/go-libp2p-pubsub#338]
I use: 

```go
blklist, _ := libp2p_pubsub.NewTimeCachedBlacklist(15 * time.Minute)
libp2p_pubsub.WithBlacklist(blklist),
pubsub, err := libp2p_pubsub.NewGossipSub(ctx, p2pHost, options...)
```

and use the `pubsub.BlacklistPeer(peer)` but the upstream dep on `whyrusleeping` imo is bad because banning peers more than once, the same peer, causes a panic on add, so to use it right, I'd need to hold the ref to the blacklist, call contained before calling add, kinda too much of a hassle to accomdate this API. 

```
func (tc *TimeCache) Add(s string) {
	_, ok := tc.M[s]
	if ok {
		panic("putting the same entry twice not supported")
	}
```

from timecache.go 

Please implement blacklist without a panic causing lib

**Comment by vyzo** [comment]
This is actually very easy to fix: just add a `Has` check in the implementation of the timecache backed blacklist.
Care for a patch?

**Comment by vyzo** [comment]
Or we might try fixing the upstream library directly to support multiple puts.

**Comment by fxfactorial** [comment]
I think fix upstream is better but can it be done quick ? I don’t know that upstream dep , how quick it can be updated

**Comment by vyzo** [comment]
fixing upstream a little more complicated I think.

**Comment by fxfactorial** [comment]
Right then we’re back at my op about soln and it’s only diff if I put it app layer or in your layer at libp2p, sounds like latter? If so , then ya , I’ll open PR

**Comment by vyzo** [comment]
It is better if we put it in the pubsub library; a pr would be very welcome!

**Comment by fxfactorial** [comment]
https://github.com/libp2p/go-libp2p-pubsub/pull/340
