### ISSUE TITLE
Feature request for gossipsub v1.1: delayed adding of topic score parameters

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#346]
Wondering if this is feasible to be implemented. 
At the current time, we have to know from the start the topic list in order to use the peer scoring feature. This will bring more complexity in a system that will have a topic list that changes in time.
Thanks

**Comment by vyzo** [comment]
Yes indeed, this would be very useful -- we plan to add an API for setting topic score parameters (and generally updating the score parameters) dynamically.

**Comment by nisdas** [comment]
Thats great to hear @vyzo ,is there an ETA for when you expect dynamic topic subscriptions to be possible for topic score parameters ? With how we use gossipsub currently in v1.0, there is a constant churn of subscribed topics, so using peer scoring in v1.1 isn't possible in the current form.

**Comment by vyzo** [comment]
Reasonably soon, I will try to get to it the next week or two.

**Comment by vyzo** [comment]
Implementation in #376; sorry that 2 weeks became 2 months, we've been really busy with other things!
