### ISSUE TITLE
Reduce memory usage for receive buffers

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-pubsub#350]
We don't need to keep around large receive buffers. Instead, we can use msgio's message reader to:

1. Read the message length with a small buffer.
2. Get a larger buffer from the buffer pool to read the rest of the message.
3. Put the larger buffer back into the pool.

See https://github.com/libp2p/go-libp2p-kad-dht/blob/c245d836ab82922314dcbc364b3763d114938aad/dht_net.go#L76-L116 for how we do this in the DHT.

![buffers](https://user-images.githubusercontent.com/310393/84423521-6ccc5100-abd3-11ea-902a-baa35fc606fd.png)

**Comment by Winterhuman** [comment]
@Stebalien Any update on this? Looks like it's been untouched for a while and is blocking https://github.com/ipfs/go-ipfs/issues/6621#issuecomment-642846010.

**Comment by amirylm** [comment]
Any update on this? we experienced the same issue https://github.com/bloxapp/ssv/issues/688

**Comment by vyzo** [comment]
@MarcoPolo would you like to take a swipe at this?

**Comment by Wondertan** [comment]
Happy to volunteer unless @MarcoPolo wants to tackle this
