### ISSUE TITLE
Cannot find remote peer if pubsub is initialized after connection established

### ISSUE THREAD

**Issue by huiscool** [libp2p/go-libp2p-pubsub#357]
Hi, I initialize a pubsub with a pre-connected host, and I find that pubsub cannot find the remote peer on a established connection, even if the remote peer also has a pubsub. The network.notifiee only tells which new peer is incoming, but it doesn't tell the connected peers. So how can I deal with this? Thanks!

**Comment by vyzo** [comment]
Yes indeed, this is the case and a problem. What we could do is scan the active connections on initialization and check whether already connected peers support one of our pubsub protocols.

**Comment by Wondertan** [comment]
Is this closed by https://github.com/libp2p/go-libp2p-pubsub/pull/393?

**Comment by huiscool** [comment]
Yep, I think #393 will resolve this problem.
