### ISSUE TITLE
pubsub.Topic should satisfy fmt.Stringer

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p-pubsub#358]
Due to the requirement of maintaining a single `*pubsub.Topic` handle per pubsub topic, it is often helpful to identify the topic to which a given handle belongs.

Common solutions include:

- `map[string]*topic.Topic`
- Defining a local topic handle that embeds `*topic.Topic`, and exposes the topic string via a `String() string` method

Seeing as how `*topic.Topic` already contains an unexported `topic` field, it would be both trivial and extremely helpful to add the following method:

```go
func (t *Topic) String() string {
    return t.topic
}
```

I'm happy to submit a PR if there's any interest.

**Comment by aschmahmann** [comment]
Sounds great, was one of the suggestions here (https://github.com/libp2p/go-libp2p-pubsub/issues/198#issuecomment-548896902) that has yet to be implemented.

Would welcome a PR.

**Comment by lthibault** [comment]
@aschmahmann Done!  Please see #370.
