### ISSUE TITLE
Gossipsub Backoffs not stored in GossipSubRouter::sendPrune

### ISSUE THREAD

**Issue by blacktemplar** [libp2p/go-libp2p-pubsub#367]
Every time we send a prune via [`GossipSubRouter::sendPrune`](https://github.com/libp2p/go-libp2p-pubsub/blob/4ccb63821e80f5f05f4894f98c2f6a90e64a1894/gossipsub.go#L1007) we include our backoff specified in the config [here](https://github.com/libp2p/go-libp2p-pubsub/blob/4ccb63821e80f5f05f4894f98c2f6a90e64a1894/gossipsub.go#L1752). But we never actually add this backoff for the given peer and topic to our data structure (we add it in many other situations like [here](https://github.com/libp2p/go-libp2p-pubsub/blob/4ccb63821e80f5f05f4894f98c2f6a90e64a1894/gossipsub.go#L684), but not in the situation where we send a `PRUNE`).

This result of this is that if we `PRUNE` a peer we might try to re`GRAFT` immediately (or shortly after) which will result in a punishment by the receiving peer because of the backoff he received. Therefore I assume this is a bug.

A scenario, where this bug might occur heavily is if we leave a topic (this calls sendPrune on all peers of this topic) and then join it again shortly after.

**Comment by vyzo** [comment]
That's not correct, we add the backoff before we invoke sendPrune; it is always stored.

**Comment by blacktemplar** [comment]
Ok, so for the calls in [`GossipsubRouter::Leave`](https://github.com/libp2p/go-libp2p-pubsub/blob/8945f91465bc3ba418688684a2c29c384cd79647/gossipsub.go#L983), where does the backoff get stored?

My scenario is: We leave a topic and then immediately join it again. Then, this will lead to many grafts that are all invalid and get punished because of the backoff.

**Comment by vyzo** [comment]
Hrm, if we do leave the topic then it is not store; the scenario of immediate rejoin (within a minute) would indeed be problematic.
Do you see this occurring in practice or is it a theoretical concern?

**Comment by blacktemplar** [comment]
The issue occurred to me because I am currently implementing Gossipsub V1.1 for rust-lang in rust-libp2p and thought of how to handle this edge case. Since the spec is not really detailed enough for such concerns, I am looking at this repository for reference.

**Comment by vyzo** [comment]
So mostly theoretical; still a valid concern however.
We could store the backoffs after we leave the topic as a solution for this -- this is something that would be straightforward to implement.

**Comment by blacktemplar** [comment]
Similar to the `GossipRouter::Leave` problem when joining a new topic the backoffs for peers to graft are not checked (is relevant if we unsubscribed from this topic a short period before).

**Comment by nisdas** [comment]
@vyzo Carrying on from #456, would there be any downside for introducing a backoff for pruned peers ?

**Comment by vyzo** [comment]
we do have backoff for pruned peers, but it is not persisted if the peer
leaves. I dont think there is much of a downside to persist it, as it will
be cleared when it expires. The one thing to be careful with would be
excessive prune times, eg an attacker launching gazillion of peers to be
pruned and stuff the backoff tracking.

**Comment by nisdas** [comment]
> The one thing to be careful with would be
excessive prune times, eg an attacker launching gazillion of peers to be
pruned and stuff the backoff tracking.

True, although that would require the attacker to be able to connect and fill up the local peer table unimpeded. If this is fine, I can open a PR to implement this.

**Comment by vyzo** [comment]
yeah, go for it.

For attack mitigation I would just set a max backoff interval to observe,
so that they are always cleaned reasonably soon.

**Comment by nisdas** [comment]
Hey @vyzo , opened up #473 to fix this case.

**Comment by BigLep** [comment]
Resolving since https://github.com/libp2p/go-libp2p-pubsub/pull/473 ws merged.
