### ISSUE TITLE
Reduce logging around redundant greylisting side-effects

### ISSUE THREAD

**Issue by placer14** [libp2p/go-libp2p-pubsub#380]
As a dev who analyses log output from apps which consume libp2p (lotus), I want greylist side-effects to not be so verbose. Both to minimize the amount of overhead needed to manage piping reduncing information to disk but also remove noise from logs for easier anaysis.

The issues are especially prevelent when the libp2p node is experiencing a DoS attack.

Example output we want to avoid:
![image](https://user-images.githubusercontent.com/305332/90983203-68f56d00-e53a-11ea-8304-12b0b5d3defa.png)

**Comment by vyzo** [comment]
What version of lotus are you running? This should be resolved in latest master, we fixed an issue around negative scores.

**Comment by vyzo** [comment]
We can certainly reduce the verbosity however.

**Comment by vyzo** [comment]
actually info is not all that verbose.

**Comment by vyzo** [comment]
also of note you can reduce subsystem verbosity directly; try
```
lotus log set-level --system pubsub warn
```

**Comment by placer14** [comment]
Thanks for the suggestion This looks to be on v0.3.4. Is there a way to apply this via environment variable or as a flag to `lotus daemon` on startup? Would rather deploy this node config more "atomically" rather than in a two-step "init->config" process.

**Comment by vyzo** [comment]
I don't know whether it can be set in the config, but we can try to find out :)
Also note that lotus master is now on v0.3.5 (and all the spacerace releases include the fixes from pre-v0.3.5 master).
