### ISSUE TITLE
How can I addPeer for Topic after Connected event ?

### ISSUE THREAD

**Issue by cc14514** [libp2p/go-libp2p-pubsub#382]
I Just find one way to add peer for pubsub , that is Connected event, but some times we would like create Topic after connect , then Topic's peers is nil now, how can I addPeer for Topic ?

**Comment by cc14514** [comment]
I get it , may be pubsub.WithReadiness can do that.

**Comment by TianshuDing** [comment]
Hi, I have the same question about this, how you fix this?
