### ISSUE TITLE
Tracing is uneasy with only the public interface

### ISSUE THREAD

**Issue by MichaelMure** [libp2p/go-libp2p-pubsub#399]
I wanted to monitor the messages dropped due to #398 but the tracing API make that difficult. I ended up writing the following (obviously not great) code:

```go
type tracer struct {
	ingressDropped *stats.Int64Measure
	egressDropped  *stats.Int64Measure
}

func (t tracer) Trace(evt *pubsub_pb.TraceEvent) {
	switch evt.GetType() {
	case pubsub_pb.TraceEvent_REJECT_MESSAGE:
		if evt.RejectMessage == nil {
			return
		}
		switch evt.RejectMessage.GetReason() {
		case "validation queue full", "validation throttled":
			stats.Record(context.Background(), t.ingressDropped.M(1))
		}
	case pubsub_pb.TraceEvent_DROP_RPC:
		stats.Record(context.Background(), t.egressDropped.M(1))
	}
}
```

This code:
- use string constants copied from the package as they are not public
- require a deep understanding of the package internals to catch the correct case
- imply that we are doing an unnecessary marshaling to a protobuf message

The internalTracer interface looks better in my opinion but it's also not publicly accessible.

**Comment by vyzo** [comment]
So the right solution for this is to simply expose the lower level interface from `internalTracer` and export the reason strings.
This should give you a more powerful hook that avoids the protobuf round trip.

**Comment by vyzo** [comment]
See #403.
