### ISSUE TITLE
feature wanted: work like message queue such as kafka

### ISSUE THREAD

**Issue by bitcard** [libp2p/go-libp2p-pubsub#400]
pubsub not support offline message at present, sub node go die for a while, and then go live, they will lost some messages. so it's necessary cache message for a perid of time, such as 24 hour. when node go online, they can consume the message, further more, add a offset to marking the consumption position.

**Comment by vyzo** [comment]
Sorry, but that's out of scope for the library.

**Comment by bitcard** [comment]
> Sorry, but that's out of scope for the library.

ok, thank you for the reply, is there a similar solution or other demo code?

**Comment by vyzo** [comment]
check go-libp2p-pubsub-router, it's using last message persistence and a side protocol for synchronization.

**Comment by bitcard** [comment]
> check go-libp2p-pubsub-router, it's using last message persistence and a side protocol for synchronization.

thank you.
