### ISSUE TITLE
GossipSub Max Message Size

### ISSUE THREAD

**Issue by iNDicat0r** [libp2p/go-libp2p-pubsub#401]
Publishing a message using the `func (p *PubSub) Publish(...)` method requires a topic and byte slice. When reading the message using `Subscription.Next` we get a protobuf message which contains the data received. However the problem is that there is a protobuf message size limit by google, in some cases 64MB is the max size. How does `go-libp2p-pubsub` handle larger messages ?

**Comment by vyzo** [comment]
The default max message size is 1MB; you can change this with the `WithMaxMessageSize` option.

However, I really don't recommend sending 64MB messages over pubsub because of amplifcation; if your messages are that large, it's better to send a content identifier and pull it with a side protocol.

**Comment by TianshuDing** [comment]
I have the question about Max Message Size. As you say, it's better to send a content idertifier and pull it with a side protocol. So, if you can, please show me some examples about this situation. And if I want to send a message to a single peer in the topic not broadcast to every peers in the topic, what option need to config the gossipPubSub?

**Comment by vyzo** [comment]
check go-libp2p-pubsub-router, it uses a side protocol for last write
persistence.

**Comment by TianshuDing** [comment]
Thank you for your advice, any really project using this? And what about the second question, do not broadcast, just send to one peer.

**Comment by vyzo** [comment]
yes, ipfs uses it.
