### ISSUE TITLE
My gossiphub subscribe NO message.

### ISSUE THREAD

**Issue by Lawliet-Chan** [libp2p/go-libp2p-pubsub#428]
Hi， I publish msg into p2p on A node and want to subscribe it  on B node. BUT I cannot accept it  because it blocked.  There are no errors return about publisher or subscriber. 
https://github.com/Lawliet-Chan/yu/blob/master/node/master/p2p_pubsub.go#L66

In a strange way,  my code has three pubsub-topic, the others can work.        Just only this one blocked.  
I found that the codes block on this line: https://github.com/Lawliet-Chan/yu/blob/master/node/master/p2p_pubsub.go#L106

How can I fix it?

**Comment by Stebalien** [comment]
Please direct questions to [discuss.libp2p.io](https://discuss.libp2p.io). We can open a new issue here if we identify a bug.
