### ISSUE TITLE
Respect Backoff For Pruned Peer

### ISSUE THREAD

**Issue by nisdas** [libp2p/go-libp2p-pubsub#456]
`Peer A` and `Peer B` are subscribed to the same topic(`Topic X`)  and have each other in their mesh for `Topic X` 

Peer A then decides to leave the topic and both remove each other from their mesh for this topic. However since `Peer B` receives a prune message from A ( due to A leaving the topic), it adds a backoff for that topic with that peer. If A rejoins `Topic X` before the backoff period ends, it will try to graft new peers into the mesh. And if peer B is still connected, Peer B will be regrafted into the mesh. However because Peer B already was pruned previously and had a backoff for that topic, it will penalize Peer A for trying to regraft it into the mesh for `Topic X`. 

The correct behaviour would be for Peer A to also add a corresponding backoff for peers that it prunes this way. That way it will know not to graft in peers who had been previously pruned and had a backoff running(and therefore unintentionally being penalised). Although this would only ever happen if the period of leaving and joining the same topic is within the prune backoff period, this edge case should be handled so that peers are not unintentionally penalised.

**Comment by nisdas** [comment]
Seems like #367 is essentially the same issue too.

**Comment by aschmahmann** [comment]
@nisdas can this be closed as a duplicate issue? cc @vyzo.

**Comment by vyzo** [comment]
wait, we do that already iirc, both sides backoff.

**Comment by vyzo** [comment]
ah the leave/join thing. Yes, duplicate afaict.

**Comment by nisdas** [comment]
Alright lets shift the conversation to #367 .
