### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by eugenechyrski** [libp2p/go-libp2p-pubsub#461]
pubsub.go#527 creates performance issue.  This  loop uses excessive processor resources. 
Feels like this loop would really appreciate some time.Sleep(time.Millisecond) inside, dropped cpu usage from 22 to 0.8 % by me

**Comment by vyzo** [comment]
Thats the pubsub main loop; no, we are not adding a sleep like that: then your throughput is capped at 1k messages per second.

Can you please be more specific about your perf issues? Sounds like you have a lot of pubsub traffic.

**Comment by eugenechyrski** [comment]
Ok i  combined together some parts. Code here is just to reproduce issue , many things are omited.  To reproduce it just run the program twice. By me it leads to 30% cpu usage(corei9) by each of the instances


[Gist](https://gist.github.com/eugenechyrski/bb0f964f0bce5e9e76448ba3049a77e8)

**Comment by vyzo** [comment]
That 30% doesnt say much, you need to see exactly which part of the loop is busy.

Maybe it is the combination of discovery, but i dont see anything to explain it.

Also note that this library is used heavily by many projects and we havent had perf problems.

**Comment by eugenechyrski** [comment]
I will  have some time this weekend to go through it

**Comment by vyzo** [comment]
thanks! If there is a perf bug we'd certainly want to know and fix it.

**Comment by eugenechyrski** [comment]
The issue was caused by the code.  Two instances of the pubsub.PubSub has been created. Had not debugged further to see what caused the issue inside, my guess is that one of the loops was spinning without taking any events

**Comment by vyzo** [comment]
sounds reasonable, thanks for investigating.
