### ISSUE TITLE
discovery.go: `MinTopicSize` does not include publishing host in `TopicSize` count.

### ISSUE THREAD

**Issue by renaynay** [libp2p/go-libp2p-pubsub#462]
`MinTopicSize` is confusing as `TopicSize` is interpreted as **total** number of peers listening in on a topic, but in reality, the publishing host excludes itself from that number. It would be nice if this were either to be documented in the godocs or if `TopicSize` were to be changed so that it includes the publishing host in the count.

**Comment by vyzo** [comment]
sure, either works; care for a pr?

**Comment by renaynay** [comment]
Sure.

**Comment by renaynay** [comment]
Sure.

**Comment by renaynay** [comment]
https://github.com/libp2p/go-libp2p-pubsub/pull/463
