### ISSUE TITLE
How nodes find each other?

### ISSUE THREAD

**Issue by VinnyVicious** [libp2p/go-libp2p-pubsub#469]
Is there any document outlining the process for a node to find one another? Does it brute scan the local network? What about nodes connected to the internet?

**Comment by vyzo** [comment]
peer discovery is very explicitly outside the scope of the protocol, with
the exception of prune PX in gossipsub (see the spec).
The library receives connection notifications and reacts accordingly; it is
up to you to use an appropriate discovery strategy for your application.

**Comment by VinnyVicious** [comment]
Ah, thank you. This wasn't very clear at first.
