### ISSUE TITLE
Signing messages with a provided private key

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#485]
Hello

Are you interested having the functionality of publishing a message with a specified private key feature? We have it ready, unit tested and tested in production. Can easily open a PR here.

Use case: we have a use case in which we want to broadcast messages from "virtual" peer IDs. Those peer IDs will never be addressable nor connectable in the whole network. This feature can help constructing nodes that act like sentinel nodes but in fact are the real nodes, broadcasting on the behalf of a virtual node that can never be found on the network nor easily traceable.

**Comment by vyzo** [comment]
Sure, lets upstream this.

**Comment by iulianpascalau** [comment]
on it

**Comment by iulianpascalau** [comment]
Related with https://github.com/libp2p/go-libp2p-pubsub/pull/486

**Comment by iulianpascalau** [comment]
I guess we can close this since the PR merged into `master` branch. Thanks.
