### ISSUE TITLE
Question regarding Gossipsub messages propagation

### ISSUE THREAD

**Issue by roaminro** [libp2p/go-libp2p-pubsub#487]
Hello!

Quick question regarding Gossipsub messages propagation. Let's say I have the following p2p network:

A <-> B <-> C

where:
- A is subscribed to topic 1
- B is subscribed to topic 2
- C is subscribed to topic 1

If A or C were to publish messages on topic 1, would B propagate these messages to C and A respectively even though it's not subsribed to topic 1?

My initial tests show that, no, C doesn't gossip messages that don't belong to topics C is subscribed to. (that's why I'd like to make sure what is the expected behavior)

Thank you in advance for the help!

**Comment by vyzo** [comment]
no, unless you enable relay for the topic.

In general, nodes only propagate messages for topics they have joined (as suscribers or relays).

**Comment by roaminro** [comment]
got it, thanks for the quick response and the explanation @vyzo !
