### ISSUE TITLE
seenMessages TTL should be based on last observed time, not first

### ISSUE THREAD

**Issue by stbrody** [libp2p/go-libp2p-pubsub#502]
The [seenMessage](https://github.com/libp2p/go-libp2p-pubsub/blob/01ab84a809990a5ceefd34bca98139617fcc5389/pubsub.go#L152) cache prevents us from processing and re-broadcasting a pubsub message that we have already seen within the `seenMsgTTL` (default 2 minutes).  Accessing an existing message, however, [does not update the timestamp associated with the entry in the cache](https://github.com/whyrusleeping/timecache/blob/cfcb2f1abfee846c430233aef0b630a946e0a5a6/timecache.go#L57-L60).

This means that if a single pubsub message is being received frequently and consistently, we'll re-broadcast it every `seenMsgTTL`, rather than never re-broadcasting it as is the desired behavior.  If every time we received a duplicate pubsub message we pushed back the expiration time in the cache, that would give us the desired behavior of never re-broadcasting a message that we have already seen within the last `seenMsgTTL` seconds.

**Comment by stbrody** [comment]
Please note that we have experienced a severe issue in the past with seeing a flood of pubsub messages suddenly come in all at once.  On closer observation we notice that many of the messages are duplicate messages that we have seen before.  We reported it a while ago against the JS implementation [here](https://github.com/libp2p/js-libp2p/issues/1043), but we have seen it more recently on go-ipfs v12 as well.  In the most recent occurrence, we never saw the same message duplicated within a 2 minute window, but would often see the same messages coming into our node every 2-3 minutes.

So I think it's possible that this relatively small change could have a significant benefit for us to avoid these quite disastrous pubsub floods that we have been experiencing sporadically.

**Comment by stbrody** [comment]
We also discussed the more recent occurrence of the pubsub flood issue in this slack thread with some PL folks, for reference: https://filecoinproject.slack.com/archives/C025ZN5LNV8/p1661459082059149

**Comment by vyzo** [comment]
This makes sense, care for a patch?

**Comment by vyzo** [comment]
Probably as an option, it can be turned on by default.

**Comment by stbrody** [comment]
@vyzo Looks like I'd have to either modify or fork the timecache library as it doesn't provide any way to update the expiration time for an existing entry (it even [errors if you try to add the same key twice](https://github.com/whyrusleeping/timecache/blob/cfcb2f1abfee846c430233aef0b630a946e0a5a6/timecache.go#L26)).  Do you know who the maintainer is?  Any idea if I'd be better off making a PR to the existing library vs forking it or making a new TTL cache implementation?

**Comment by vyzo** [comment]
It's not really maintained, we should probably move it in tree.

**Comment by smrz2001** [comment]
Hey @vyzo, I just put up a [PR](https://github.com/libp2p/go-libp2p-pubsub/pull/513) for this issue. Please take a look when you get a chance 🙏🏼
