### ISSUE TITLE
panic: putting same entry twice not supported

### ISSUE THREAD

**Issue by AskAlexSharov** [libp2p/go-libp2p-pubsub#521]
<img width="885" alt="Screenshot 2023-02-20 at 13 57 54" src="https://user-images.githubusercontent.com/46885206/220034833-78618440-2501-4088-82d5-e8b114f7c285.png">

**Comment by vyzo** [comment]
Ouch, seems our newly incorporated cache has a bug.

**Comment by Wondertan** [comment]
Our nodes are crashing because of this, and we need this fixed ASAP. If no one is working on this, we can take it,

**Comment by vyzo** [comment]
sure, go ahead.

Correct behaviour is to ignore the message.

**Comment by Wondertan** [comment]
The `Has` on cache is checked [here](https://github.com/libp2p/go-libp2p-pubsub/blob/cda3df70f42af335322cf4cf77f58fff84b32cff/pubsub.go#L998) with correct synchronization. However, false from `Has` [can be returned](https://github.com/libp2p/go-libp2p-pubsub/blob/cda3df70f42af335322cf4cf77f58fff84b32cff/timecache/first_seen_cache.go#L70) even if the message already in the cache, because the message is outdated(time since first seen > TTL)

**Comment by Wondertan** [comment]
We can either: 
* Simply don't panic and ignore the message
* Or sweep the message in place on Has when the time since first seen > TTL
	* This way panic will never be triggered

**Comment by Wondertan** [comment]
I am fine with both, but my intuition inclines toward the second option. WDYT, @vyzo

**Comment by vyzo** [comment]
just ignore the message i would say, panic is very bad.

**Comment by vyzo** [comment]
dont do the sweep in Has, will need xlock.

**Comment by vyzo** [comment]
Also, we need to implement background sweeping at some point, for both cache impls, as this eager sweep business has implications for locking.

**Comment by Wondertan** [comment]
There are many places where processLoop is locked unnecessarily :) 
Network.Connectedness can look it for a while

**Comment by Wondertan** [comment]
> dont do the sweep in Has, will need xlock.

I know, but it seemed fine. Though background sweeping is a better approach so, let's just remove panic for now, as you've said

**Comment by vyzo** [comment]
yeah, although we try to make it fast.

But point taken, ok, lets fix Has.

But please do remove the panic, it needs to ignore the message (and maybe log something in debug).

**Comment by vyzo** [comment]
We are racing ;)

To summarize:
Lets fix Has while at it.
If you feel so inclined, feel free to do bg sweeping.

Other than that, the panic must go.

**Comment by vyzo** [comment]
More generally, if we are using bg sweeping, we can greatly simplify everything.

We dont need queues, just a map of mid to expiry.
Has shouldnt even check time, just map presence.
And bg sweeping just clears everything expired.

We can and should do for both implementations.

**Comment by Wondertan** [comment]
Ok, bg sweeping can be done in a separate PR. Let's remove the panic as a start: https://github.com/libp2p/go-libp2p-pubsub/pull/522.

**Comment by Wondertan** [comment]
@vyzo, mind releasing a patch?

**Comment by vyzo** [comment]
We certainly can, but i was thinking of doing bg sweeping first (unless you want to do it).

**Comment by Wondertan** [comment]
Fair, no need to keep that tech debt around.
