### ISSUE TITLE
`SetTopicScoreParams` after join a new pubsub topic

### ISSUE THREAD

**Issue by richard-ramos** [libp2p/go-libp2p-pubsub#533]
I noticed [here](https://github.com/libp2p/go-libp2p-pubsub/blob/master/score.go#L205-L210C2) that if a topic has not been setup before as part of the `WithPeerScore` option, then the `exist` variable will always be false, so it seems that it isn't it possible to set the `TopicScoreParams` with `SetTopicScoreParams` for new topics **after** GossipSub has been instantiated. 
```go
	old, exist := ps.params.Topics[topic]
	ps.params.Topics[topic] = p

	if !exist {
		return nil
	}
```
Is this a bug or intended behavior? because if remove the `if !exist {` condition, the logic seems to work fine when joining any new pubsub topic.

**Comment by vyzo** [comment]
Hrm, i think we can call it a bug; pr welcome.
