### ISSUE TITLE
feature: Prune should include an optional reason

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p-pubsub#535]
It would be very helpful for debugging and health monitoring of the network to know why a peer pruned us. Even if they only tell we were pruned because our score became negative that would be helpful.

I don't think there's a security issue here since a node can essentially infer it is misbehaving if many peers prune at once. This just makes that explicit.

**Comment by vyzo** [comment]
I dont think this adds anything to the protocol, other than increasing bandwisth use.

**Comment by vyzo** [comment]
Also, that would require a spec change, this is not the place to directly implement without discussion in the specs with community.

**Comment by MarcoPolo** [comment]
We can have a single bit for “because your score is negative”

**Comment by vyzo** [comment]
Maybe, but again this should be discussed with the community.
I still think it is of marginal utily, if any.

**Comment by MarcoPolo** [comment]
> Also, that would require a spec change, this is not the place to directly implement without discussion in the specs with community.

Thanks, good point.

**Comment by MarcoPolo** [comment]
https://github.com/libp2p/specs/issues/555
