### ISSUE TITLE
Gossip mesh includes all peers in the network

### ISSUE THREAD

**Issue by sarvalabs-rahul** [libp2p/go-libp2p-pubsub#543]
Hi,

I'm utilizing a gossip-based pubsub for broadcasting blocks. We currently have a testnet consisting of 400 nodes, with each node subscribed to this specific topic. When I check the list of peers for this topic on a specific node, it returns 400 . How can I restrict the number of peers for each topic?

Here are the gossipParams:
Dlo = 6
D = 8
Dhi = 16

**Comment by vyzo** [comment]
these are not your mesh peers, but all you peers who support the protocol.

**Comment by sarvalabs-rahul** [comment]
@vyzo But i could see active mesh connections among all the peers, I have used `host.Network().Conns()` to retrieve the active connections. 

Total no.of mesh connections for a peer is very close to the no.of peers in the entire network.

**Comment by vyzo** [comment]
This are _not_ mesh connections.

**Comment by vyzo** [comment]
that's an issue of your peer discovery and bootstrap mechanism; nothing to do with gossipsub.

**Comment by sarvalabs-rahul** [comment]
@vyzo, I could see that each peer has at least one  active stream with "/meshsub/1.1.0"  protocol.ID  with all other peers.

Am i missing anything ?

**Comment by vyzo** [comment]
the protocol automatically hanshakes; it doesn't mean they are in the mesh.

In short, this is neither a bug not a problem at all.

**Comment by sarvalabs-rahul** [comment]
@vyzo 
Here are my last set of questions:
- Does the peer initiate a stream for the handshake for every subscribed topic?
- If affirmative, are the streams terminated once they surpass the predefined resource manager thresholds ?

Context:
I am currently developing a context-aware blockchain protocol. In this protocol, we create temporary dynamic clusters in runtime to handle transactions based on the contextual information of participants and their interactions.

Within our protocol, each node can participate in multiple clusters concurrently and process transactions in parallel. This places significant strain on the network, prompting us to explore optimisation possibilities.

Thank you for taking the time to address my questions.

**Comment by vyzo** [comment]
no, there is one inbound and one outbound stream total.
