### ISSUE TITLE
New release compatible with go-libp2p v0.32

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p-pubsub#547]
go-libp2p v0.32 removes `peer.ID.Pretty` method. That makes the latest release v0.9.3 incompatible with go-libp2p v0.32. Can we cut a new patch release?

**Comment by vyzo** [comment]
Sure, we can do that.

**Comment by vyzo** [comment]
Care for a patch to bump libp2p to v0.32?
We can then make a minor release.
