### ISSUE TITLE
Query: Access to topic level peer scores to application layer

### ISSUE THREAD

**Issue by chaitanyaprem** [libp2p/go-libp2p-pubsub#554]
I would like to know if there is a way to access current peer scores at application layer.

I went through the gossipsub code and found that peerScores are internal and are not exposed. Is there any other way to access these?

This would help us indicate status of the peer connection health in application in case scores to all peers are low (which could just be due to bad internet connectivity which delays packets received).
This could be used to indicate bad network health.

**Comment by vyzo** [comment]
yes, you can get a periodic callback with a copy of the score table for exactly this purpose.

**Comment by vyzo** [comment]
See WithPeerScoreInspect in score.go.
