### ISSUE TITLE
Validation requires parsing messages twice

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-libp2p-pubsub#66]
I've been exploring the recently added `Validator` functionality, which is very nice - however there is one (probably unintended) aspect of it that I found interesting.  If I need to validate the contents of a message - say it's protobuf encoded - then I need to parse it once when validating, and potentially another time, after actually receiving the (`[]byte`) data through `subscription.Next()`.  I don't think it's a major issue, and there might not be a clean way to solve it.

**Comment by iulianpascalau** [comment]
Also thought of that and currently, as a work around, you can buffer the deserialized object in a `timecache`. All you need to do is 2 extra hash calculations (one when validating data and one when trying to retrieve the data from cache) + an insert to cache and retrieve from cache. It should improve performance.

**Comment by vyzo** [comment]
We have added a filed in the Message struct that includes optional validation data; this could be used by a validator to pass a decoded message to the application.
