### ISSUE TITLE
Maximum number of nodes in a gossipsub network.

### ISSUE THREAD

**Issue by jamesray1** [libp2p/go-libp2p-pubsub#86]
For the latest [Ethereum sharding + Casper spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#), the theoretical maximum of validators (assuming a supply cap of 128m ETH) is 4m. This conflicts with the target size of 10,000 in https://github.com/libp2p/specs/tree/master/pubsub/gossipsub#membership-management-protocol. 10,000 won't even be OK initially, since there are 16,825 nodes as I write this. Dynamic sizing is needed support up to 4,000,000 (or more) will be needed eventually, and 20,000 will be needed initially.

Two models have been proposed for the network layer: one network for each shard, or a [torus shaped network](https://ethresear.ch/t/torus-shaped-sharding-network/1720), where a node mostly communicates with nodes in the same shard, while propagation of messages between shards are limited to a certain intra-shard distance, and to certain types of messages such as new collations, e.g. a node in shard 2018 (there could be up to 4096 shards in total) can relay new collations to notaries between shards 2013-2023, while these notaries may be shuffled to shard 2018 soon (while possibly notaries in one shard may be shuffled to a shard up to n, say 5, shards away in the next period).

I'll cross-post this on the above ethresear.ch thread and in issue #77.

Assuming N = 4,000,000 then C_rand = 7.

**Comment by whyrusleeping** [comment]
Our pubsub implementations plan to scale far beyond 10,000 nodes. The number 10,000 in that doc is used to derive sane parameters for the current size of the ipfs network. Any number may be chosen in order to derive the other parameters for a network of that size, and as it mentions, we will be working to make these parameters dynamic (a protocol for dynamically adjusting network parameters in a secure way is a bit larger challenge, and we're going to worry about that later)

**Comment by mhchia** [comment]
Thank @jamesray1 for pointing it out. (Might be better if we track it in ethresear.ch or other places?) IMO 10,000 nodes should be enough in the short-term. We can try how to scale it after we have simulation/tests/testnet at that scale?

**Comment by tim-coin** [comment]
@jamesray1 We have implemented a "somewhat" torus network where nodes of Type-1 connect to shards only and some nodes of Type-2 connect to all other shards' Type-2. This way we have limited the total combinations possible and de-clogging.  10,000 should be enough for 2/3 years, after which a boost would be required.
I am working on overcoming this 10K limit in that timeline.

**Comment by whyrusleeping** [comment]
Just to clarify my comment, the 10,000 'limit' isnt a limit. Its a choice of parameters. You can pick a bigger number and adjust the parameters to fit that.

**Comment by vyzo** [comment]
Just a few thoughts on the subject.
I ran some simulations, and the baseline meshsub constructor consistently produces connected overlays at 1M nodes.
In fact, it does so with even `D_lo = 2, D_hi = 3`.
So as long as there is good connectivity in the network, I think you should be able to easily scale up to that number with the default parameters (and have good latency/amplification indicators).
