### ISSUE TITLE
Naming & modularization

### ISSUE THREAD

**Issue by daviddias** [libp2p/go-libp2p-pubsub#89]
To avoid future confusion such as -- https://github.com/libp2p/go-floodsub/pull/67#issuecomment-404491392 --. I want to propose that we adopt the following:

- go-pubsub - The pubsub API and the thing that knows how to take multiple pubsub implementation
- go-floodsub - The floodsub implementation
- go-gossipsub - The gossipsub implementation

This will make it very clear that libp2p/IPFS support multiple pubsub implementations and that we encourage everyone to try new ones.

**Comment by Stebalien** [comment]
My current plan is to:

1. Remove the current `go-libp2p-pubsub`.
2. Rename this package to `go-libp2p-pubsub`.
3. Eventually extract the floodsub/gossiphub from it.

The implementations are currently bundled with this repo as we'll probably need to refactor things quite a bit to get the interfaces right.

**Comment by hsanjuan** [comment]
We can proceed with this at this point?

**Comment by vyzo** [comment]
We can probably proceed with steb's 1&2.

**Comment by daviddias** [comment]
This is now solved.
