### ISSUE TITLE
Dialed wrong peer in test

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-pubsub#90]
TestGossipsubFanoutMaintenance returned `dial attempt failed: <peer.ID aAAbZQ> --> <peer.ID W49xHM> dial attempt failed: connected to wrong peer`. That's really weird.

**Comment by daviddias** [comment]
Follow on https://github.com/libp2p/go-libp2p-pubsub/issues/202 (centralizing all the issues that refer to flaky tests)
