### ISSUE TITLE
Add connection manager tagging

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-pubsub#91]
We need to start tagging connections that are useful to us through the [connection manager](https://github.com/libp2p/go-libp2p-interface-connmgr/blob/master/interface.go#L11)

For example, in the DHT, we tag any peer that goes into our routing table with a value of 5.
We should likely tag peers that are in pubsub topics that we are subscribed to, or that we publish to.

**Comment by mhchia** [comment]
Thank you for keeping track of it. It will be a lot helpful for peer management!

**Comment by thomas92911** [comment]
referenced this issue
[go-libp2p Improved Connection Manager #475](https://github.com/libp2p/go-libp2p/issues/475#issuecomment-438899722)

**Comment by vyzo** [comment]
it's already implemented for gossipsub; i don't see a reasonable way to do it for floodsub as this would tag a potentially unbounded number of connections.
