### ISSUE TITLE
Gossipsub membership implementation

### ISSUE THREAD

**Issue by jannikluhn** [libp2p/go-libp2p-pubsub#92]
The [Gossipsub spec](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub) contains a membership management protocol which doesn't seem to be implemented here. Is this still on the roadmap? If not, what is the alternative? Also, is the spec itself final already or is it work in progress?

**Comment by mhchia** [comment]
It seems the current codebase is much more close to the protocol described in https://github.com/vyzo/gerbil-simsub.

Besides, I'm also curious if the peer shuffling mechanism for partial view management will be implemented. It seems to be important to the protocols using partial view. Or is it already implicitly implemented?

cc @whyrusleeping @vyzo 
Really appreciate:)

**Comment by whyrusleeping** [comment]
Yeah, the confusing bit here is the naming (as mentioned in a different issue) there is the gossipsub implementation that is a good 'next step' along the path, and the 'gossipsub spec draft' that is a WIP draft of the system we want to build. The spec draft should get a better name. Also, review is *very* welcome on that draft.

We should also write up a spec for the gossipsub implementation as it exists in the codebase (and floodsub while we're at it). One of the main purposes behind that implementation was to pave the way for more interesting and complicated systems to be built.

**Comment by vyzo** [comment]
Ok, I think there is some confusion here -- the gossipsub spec that got checked in doesn't correspond to the protocol implementation.
Rather, it is based on an earlier proposal for epidemic proximity aware pubsub, which is planned for the next iteration of the protocol.

**Comment by vyzo** [comment]
Closing this as it was based on the wrong spec.
