### ISSUE TITLE
Data race in gossipsub piggybacking

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-pubsub#98]
`GossipSubRouter.sendRPC` calls `gs.piggybackGossip` on a shared RPC object. It should probably copy it first.

**Comment by vyzo** [comment]
Hrm, it actually owns the RPC object, doesn't it?
We want to avoid copying where possible.

**Comment by vyzo** [comment]
Is this something `go vet` complained about?

**Comment by vyzo** [comment]
The code looks very much correct to me, I don't see any actual race in the usage patterns of RPC objects.

**Comment by Stebalien** [comment]
The race detector complained. It may actually be that the Control field is shared.

> Hrm, it actually owns the RPC object, doesn't it?

In `Publish`, at least, the RPC is shared. I think the issue is that we modify it, send i tout at the bottom of `sendRPC` (over a channel), and then call `sendRPC` again from `Publish`.

**Comment by vyzo** [comment]
hrm, that's plausible.

**Comment by vyzo** [comment]
i think this may be a bug.
